## Exercise 1.A Numpy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [3]:
# Create arrA and print

In [4]:
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
# Loop through the first dimension 

In [6]:
for x in arrA:
    for y in x:
        print(y * 2)
    

22
24
26
28
30
32


In [7]:
# Difference between loops:
# The first loop multiplies each row by 2.
# The second loop multiplies each individual number by 2.

In [8]:
# loop through second dimension again

In [10]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


In [12]:
# This result is different because x is a whole row, 
# x * 2 multiplies the entire row instead of one value.

## Joining and Stacking Arrays 

In [13]:
# Concatenate arrA with arrA on axis=0
joined_array_1 = np.concatenate((arrA, arrA), axis=0)

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [14]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [15]:
# Stack joined_array_1 with itself
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [16]:
# Stack joined_array_1 with joined_array_2
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)

ValueError: all input arrays must have the same shape

In [17]:
# This causes a ValueError because the arrays do not have the same shape.
# joined_array_1 has shape (4, 3)
# joined_array_2 has shape (2, 6)
# np.stack() only works when all arrays have identical dimensions.

In [18]:
# Concatenate joined_array_1 with arrA
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [19]:
# Concatenate joined_array_1 with arrA on axis=1
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)

# This gives an error because the arrays do not have the same number of rows.
# joined_array_1 has 4 rows while arrA has 2 rows.
# Arrays must match in size except for the axis being joined.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [20]:
# hstack joins arrays horizontally (side by side)
h_array = np.hstack((arrA, arrA))
print(h_array)

# vstack joins arrays vertically (on top of each other)
v_array = np.vstack((arrA, arrA))
print(v_array)

# dstack stacks arrays depth-wise (creates a third dimension)
d_array = np.dstack((arrA, arrA))
print(d_array)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays 

In [21]:
# Split joined_array_1 into 2 arrays
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [22]:
# Result explanation:
# The result displayed 2 separate arrays.
# Each array is still 2-dimensional.
# Each split array has 2 rows and 3 columns.

In [24]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [25]:
# Result explanation:
# The result contains 3 separate arrays.
# Each array is 2-dimensional.
# Because 4 rows cannot be divided evenly into 3 parts,
# some arrays contain more rows than others.

## Searching and Replacing Array Values 