# Exercise 1.B Numpy Random

In [5]:
import numpy as np

## Generating Random Numbers

In [7]:
# random int between 1 and 20, 2 elements

r_1 = np.random.randint(1, 21, size =2) #randint stops before last number 

print(r_1)

[8 8]


In [10]:
r_2 = np.random.randint(1, 21, size=(1,2)) 
print(r_2)

[[ 9 15]]


In [12]:
# random.rand already knows 0 to 1 so only shape is specified 
r_3 = np.random.rand(2,1) 
print(r_3)

[[0.43598525]
 [0.72597291]]


In [13]:
r_4 = np.random.randint(20, 101, size=(4,5)) #using 101 since 100 needs to be included 

print(r_4)

[[55 59 57 88 77]
 [82 86 71 71 78]
 [65 76 89 65 30]
 [70 65 66 23 72]]


## Generating Random choices from an Array

In [14]:
students = np.array([
    "Naomi", "Corey", "Luis", "Alexus",
    "Victoria", "Samia", "Lesley","Blake",
    "Mohammed", "Charles", "Danait", "Hannah"
])

In [21]:
call_on = np.random.choice(students)

print(call_on)

Hannah


In [28]:
# breakout rooms 3 rows, 4 columns
# choice() can repeat names unless you tell it not to

breakout_groups = np.random.choice(students, size=(3,4), replace=False) # by using replace=false it prevents duplicates

In [29]:
print(breakout_groups)

[['Charles' 'Alexus' 'Luis' 'Mohammed']
 ['Hannah' 'Blake' 'Victoria' 'Danait']
 ['Lesley' 'Naomi' 'Corey' 'Samia']]


In [31]:
# I dont believe this would be the best approach to create breakout groups as students can repeat. 

In [34]:
# probability values
# Naomi = 30%
# Corey = 0%
# everyone else has remaining 70%
p_values = [
    0.30,  # Naomi
    0.00,  # Corey
    0.07,  # Luis
    0.07,  # Alexus
    0.07,  # Victoria
    0.07,  # Samia
    0.07,  # Lesley
    0.07,  # Blake
    0.07,  # Mohammed
    0.07,  # Charles
    0.07,  # Danait
    0.07   # Hanna
]

In [35]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=p_values
)

print(call_on_weighted)

['Danait' 'Victoria' 'Danait' 'Charles' 'Alexus']


## Generating a Normal Distribution

In [37]:
# np.random.normal(mean, standard_dev, size) 
bell_curve = np.random.normal(10,5, size=(4,5))

print(bell_curve)

[[12.51907032 13.08642919 12.37670868  7.45375312  7.02681249]
 [ 7.77196959  2.0503952   0.10124514  8.52226441 17.03430305]
 [14.10201465  4.47474523  5.85423297 19.10304997  9.85448399]
 [ 5.17911762 15.50016504  4.72049576  4.83519978  0.23307105]]
