# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [6]:
r_1 = np.random.randint(1, 21, size=2)

r_2 = np.random.randint(1, 21, size=(1,2))

r_3 = np.random.rand(2,1)

r_4 = np.random.randint(20, 101, size=(4,5))

r_5 = np.random.rand(4,5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[4 5]
[[17  5]]
[[0.13507712]
 [0.11468508]]
[[63 82 50 58 35]
 [61 92 89 63 86]
 [42 71 49 33 84]
 [24 44 96 21 98]]
[[0.50062615 0.50510039 0.98301354 0.46573967 0.15951072]
 [0.16916853 0.22589626 0.67615918 0.51151917 0.33414316]
 [0.20896804 0.96144965 0.23645148 0.95053054 0.43437851]
 [0.40460619 0.25457264 0.91635163 0.35571042 0.10425251]]


## Permutations

In [8]:
print(r_4)

[[42 71 49 33 84]
 [61 92 89 63 86]
 [63 82 50 58 35]
 [24 44 96 21 98]]


In [9]:
np.random.shuffle(r_4)

print(r_4)

[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]


In [10]:
# the rows moved around but the numbers inside each row stayed together.

In [12]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)

print(r_4)

[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]
[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]


In [15]:
# memorization trick 
# shuffle: mix up array (like shuffling a deck of cards)
# permutation: make me a shuffled copy ( like making a photocopy of the deck first, then shuffling the copy. original stays safe)

In [14]:
# Permutation creates a new shuffled version but does not change the original array.

shuffle() changes the original array by rearranging its rows. 
permutation() creates a shuffled copy of the array leaving the original array unchanged.

I would use shuffle  when I want to permanently randomize an array, and permutation when I want to keep the original data unchanged.

## Mathematical Operations

In [16]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

[4 5]
(2,)
[[17  5]]
(1, 2)


In [17]:
result = np.add(r_1, r_2)

print(result)
print(result.shape)

[[21 10]]
(1, 2)


In [18]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

[4 5]
(2,)
[[0.13507712]
 [0.11468508]]
(2, 1)


In [19]:
result = np.add(r_1, r_3)

print(result)
print(result.shape)

[[4.13507712 5.13507712]
 [4.11468508 5.11468508]]
(2, 2)


In [20]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result = np.add(r_2, r_4)

[[17  5]]
(1, 2)
[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [21]:
# An error message displayed because the dimensions dont match. 
# r_4 has 5 positions and r_2 has only 2 positions.
# numpy cant figure out how to get 2 values across 5 columns. 

In [22]:
print(r_1)
print(r_1.shape)

print(r_4)
print(r_4.shape)

result = np.add(r_1, r_4)

[4 5]
(2,)
[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [23]:
# r_1 and r_4 also failed because broadcasting only works if dimensions are the same 
# or one dimension is 1. 

In [24]:
print(np.add(np.array([1]), r_4))

[[62 93 90 64 87]
 [25 45 97 22 99]
 [43 72 50 34 85]
 [64 83 51 59 36]]


In [25]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[62 93 90 64 87]
 [25 45 97 22 99]
 [43 72 50 34 85]
 [64 83 51 59 36]]


In [26]:
print(np.add(np.array([[1],[1]]), r_4))

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [27]:
# broadcasting error 

Broadcasting is when NumPy lets you do math with arrays that don’t have the same shape by stretching the smaller array to match the bigger one.

Using the add function, NumPy adds values together  after it lines up the shapes as best as it can. If one array is smaller or has a single value, it gets repeated across rows or columns so the operation can still work.

The shape of the result depends on the larger array and whether the smaller array can be stretched to match it. If the shapes don’t match and can’t be broadcasted, NumPy will give an error.

## Rounding 

In [28]:
print(r_3)  # will display original float values I'm working with

[[0.13507712]
 [0.11468508]]


In [29]:
np.trunc(r_3)  # removes everything after decimal point

array([[0.],
       [0.]])

In [30]:
np.fix(r_3) # similar to trunc but always moves towards 0

array([[0.],
       [0.]])

In [31]:
np.floor(r_3) #always round down

array([[0.],
       [0.]])

In [32]:
np.ceil(r_3)

array([[1.],
       [1.]])

In [33]:
np.round(r_3,2) # round 2 decimal places

array([[0.14],
       [0.11]])

## Cumulative Operations

In [34]:
print(r_4)

[[61 92 89 63 86]
 [24 44 96 21 98]
 [42 71 49 33 84]
 [63 82 50 58 35]]


In [35]:
np.sum(r_4) # adds every single number in whole array

np.int64(1241)

In [36]:
np.sum(r_4, axis=0) # columns added downward

array([190, 289, 284, 175, 303])

In [37]:
np.sum(r_4, axis=1) # rows added sideways

array([391, 283, 279, 288])

In [38]:
np.cumsum(r_4) # running total

array([  61,  153,  242,  305,  391,  415,  459,  555,  576,  674,  716,
        787,  836,  869,  953, 1016, 1098, 1148, 1206, 1241])

## Grocery Problem

In [41]:
# 2 vegetables, 3 fruits, 4 snacks, 0 bev
bag1 = np.array([2, 3, 4, 0])

print(bag1)

[2 3 4 0]


In [43]:
# 0 fruits, 4 vegetables, 2 bev, 1 snack
bag2 = np.array([4, 0, 1, 2])
print(bag2)

[4 0 1 2]


In [45]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)

print(f"The first bag contains {total_bag1} items, and the second bag containts {total_bag2} items.")

The first bag contains 9 items, and the second bag containts 7 items.


In [46]:
total_categories = bag1 + bag2

print(f"There are {total_categories[0]} vegetables, {total_categories[1]} fruits, {total_categories[2]} boxes of snacks, and {total_categories[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [47]:
ali = np.array([5, 4, 6, 4, 2])

print(ali)

[5 4 6 4 2]


In [52]:
ben = np.array([0, 5, 5, 3, 4]) # added monday to avoid error message 

print(ben)

[0 5 5 3 4]


In [53]:
carla = np.array([3, 6, 0, 3, 4])

print(carla)

[3 6 0 3 4]


In [54]:
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [60]:
daily_total = np.sum(all_knocks, axis=0)
print(daily_total)

[ 8 15 11 10 10]


In [61]:
rolling_knocks = np.cumsum(daily_total)
print(rolling_knocks)

[ 8 23 34 44 54]


In [62]:
estimated_votes = rolling_knocks * 0.5
print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]


In [64]:
# Daily total knocks for the whole group
daily_total = all_knocks.sum(axis=0)

# Estimated votes per day 
estimated_votes = daily_total /2

print(estimated_votes)

[4.  7.5 5.5 5.  5. ]
