## Sorting arrays

In [3]:
import numpy as np

In [6]:
# using randint() to create a randomized array of integer 

In [8]:
sales_figures = np.random.randint(100, size = (3, 4, 5)) 
print(sales_figures)

[[[18 25 55 23  9]
  [37 55 23 55 48]
  [60 90 27 55 72]
  [34 55 85 51 96]]

 [[ 6 81 28 58 68]
  [10 82  2  8 15]
  [68 51 73 36 66]
  [52 44  9 47 35]]

 [[57 18 12 59 39]
  [ 7 83  1 98 44]
  [87 95 86 95 29]
  [20 60 38 36 22]]]


In [12]:
# practice with sort ()   #not in place function, will return copy of array with sorting applied

print(np.sort(sales_figures, axis = 0))

[[[ 9 18 23 25 55]
  [23 37 48 55 55]
  [27 55 60 72 90]
  [34 51 55 85 96]]

 [[ 6 28 58 68 81]
  [ 2  8 10 15 82]
  [36 51 66 68 73]
  [ 9 35 44 47 52]]

 [[12 18 39 57 59]
  [ 1  7 44 83 98]
  [29 86 87 95 95]
  [20 22 36 38 60]]]


In [10]:
print(sales_figures)

[[[18 25 55 23  9]
  [37 55 23 55 48]
  [60 90 27 55 72]
  [34 55 85 51 96]]

 [[ 6 81 28 58 68]
  [10 82  2  8 15]
  [68 51 73 36 66]
  [52 44  9 47 35]]

 [[57 18 12 59 39]
  [ 7 83  1 98 44]
  [87 95 86 95 29]
  [20 60 38 36 22]]]


In [19]:
product_num = np.array(['A100', 1073, 'AA3R5', 'XP879', '#54X', 1074, '10735P', 'M1-X', 'M2-X', 'M10-X' ])

In [21]:
# you can sort numbers and strings in the same list, but will all be treated as 
# and sorted as strings 

In [20]:
print(np.sort(product_num))

['#54X' '1073' '10735P' '1074' 'A100' 'AA3R5' 'M1-X' 'M10-X' 'M2-X'
 'XP879']


## Filtering on arrays using a condition

In [22]:
# pg 15 in student guide 

In [27]:
products_m = product_num ['M1-X' in product_num] # not good example may need loop w this 
print(products_m)

[['A100' '1073' 'AA3R5' 'XP879' '#54X' '1074' '10735P' 'M1-X' 'M2-X'
  'M10-X']]


In [26]:
sales_over_50 = sales_figures[sales_figures > 50]
print(sales_over_50)
print(sales_over_50.dtype)

[55 55 55 60 90 55 72 55 85 51 96 81 58 68 82 68 51 73 66 52 57 59 83 98
 87 95 86 95 60]
int32


In [28]:
products_m = product_num ['M1-X' in product_num]
print(products_m)

products_m2 = product_num ['M1-X' in product_num] # not good example may need loop w this 
print(products_m2)

[['A100' '1073' 'AA3R5' 'XP879' '#54X' '1074' '10735P' 'M1-X' 'M2-X'
  'M10-X']]
[['A100' '1073' 'AA3R5' 'XP879' '#54X' '1074' '10735P' 'M1-X' 'M2-X'
  'M10-X']]


In [30]:
cond1 = sales_figures <= 50
print(sales_figures[cond1])

[18 25 23  9 37 23 48 27 34  6 28 10  2  8 15 36 44  9 47 35 18 12 39  7
  1 44 29 20 38 36 22]


## Working with NumPy's Random

In [32]:
# we saw randint() generates random integers

print(np.random.randint(10))

print(np.random.randint(10, 100))

print(np.random.randint(10, 100, size = (2,5))) #2 outer elements and each have 5 values

8
11
[[40 66 61 75 69]
 [31 32 81 57 74]]


In [34]:
# rand() is going to generate a random float btwn 0 and 1 

print(np.random.rand())

print(np.random.rand(2, 3))

0.0750818069481336
[[0.57154441 0.52934748 0.76776018]
 [0.6441068  0.29156785 0.25775255]]


In [35]:
# Numpy choice() can be used to sample from an array 

print(np.random.choice(product_num))

print(np.random.choice(product_num, size = (2, 3)))

#54X
[['1073' 'A100' 'AA3R5']
 ['M1-X' 'M2-X' '10735P']]


In [37]:
pets = ['cat', 'dog','bunny','snake', 'fish']

sales_this_week = np.random.choice(pets, p= [.2, .1, .6, 0, .1],size = 10)

print(sales_this_week)

['bunny' 'dog' 'bunny' 'bunny' 'cat' 'dog' 'bunny' 'dog' 'bunny' 'bunny']


## Creating a normal distribution using normal()

In [38]:
x = np.random.normal(loc=5, scale=2, size=(30))

print(x)

[ 2.29894492  3.17326062  6.23993408  7.89387924  7.58642706  6.94817037
  4.28659693  4.30500255  3.46071238  7.6821862   2.11583116  7.06877089
  3.09409861  5.22935487  4.36247554  8.14285614  4.6731161   6.21074279
 10.1163237   1.64212407  6.65703008  3.61314001  4.60665677  0.77095338
  2.90609512  3.48158783  5.49349209  3.19403076  7.76456245 10.03034011]


In [40]:
y = np.random.normal(loc=5, scale=2, size=(10))
print(y)

[5.01328643 3.6995733  6.61911337 4.78048242 7.75648273 3.91256685
 3.99380504 6.51596602 8.98188816 5.47561495]


In [41]:
# there are other distributions like the pareto distribution 

## Manipulating arrays

In [42]:
# shuffle and permutation (different ways the same data can be ordered)
# shuffle is going to reorder the original array (in-place)
# permutation is going to return a new array with values in a shuffled order 

In [45]:
grocery_prices = np.array([2.30, 4.99, 3.75, 11.00, 1.99])

print(grocery_prices)

print(np.random.permutation(grocery_prices))

print(grocery_prices)

[ 2.3   4.99  3.75 11.    1.99]
[ 3.75  2.3   4.99  1.99 11.  ]
[ 2.3   4.99  3.75 11.    1.99]


In [46]:
# using shuffle 
print(grocery_prices)

print(np.random.shuffle(grocery_prices)) # shuffles the values in place, doesnt return a value

print(grocery_prices)

[ 2.3   4.99  3.75 11.    1.99]
None
[ 1.99 11.    3.75  2.3   4.99]


## NumPy ufuncs

In [47]:
# example using plain old mulitplication

In [48]:
discount = np.array([.1, .15, .1, .15, .2])

print(grocery_prices * discount)

[0.199 1.65  0.375 0.345 0.998]


In [49]:
print(np.multiply(grocery_prices, discount)) # a lot faster in computer  processing 

[0.199 1.65  0.375 0.345 0.998]


In [50]:
print(np.add(grocery_prices, grocery_prices))

[ 3.98 22.    7.5   4.6   9.98]


In [52]:
new_prices = np.array([1.2, 1.5, 1.9, 2.2, 2.5, 2.9, 3.5, 4.5])

# if halfway between values (e.g 1.5, 2.5) Numpy rounds to the nearest EVEN integer 

print(np.round(new_prices))

[1. 2. 2. 2. 2. 3. 4. 4.]


In [53]:
# sum() lets you add up the elements in an array 

print(np.sum(grocery_prices))

24.03


In [55]:
groc_price_2 = np.array([[2, 3, 4, 5, 10], [6, 7, 2, 1, 4]])

print(groc_price_2)

[[ 2  3  4  5 10]
 [ 6  7  2  1  4]]


In [56]:
print(np.sum(groc_price_2))

44


In [57]:
print(np.sum(groc_price_2, axis = 1)) # sum can work on specified axis

[24 20]


In [59]:
# cumulative sum provides a rolling total / rolling sum of values 
# helpful when charting performance over time 

print(np.cumsum(groc_price_2))

[ 2  5  9 14 24 30 37 39 40 44]


In [60]:
# theres prod() to multiply all values in array 

print(np.prod(groc_price_2))

403200


In [62]:
# diff() successive different elements

print(groc_price_2)

print(np.diff(groc_price_2))

[[ 2  3  4  5 10]
 [ 6  7  2  1  4]]
[[ 1  1  1  5]
 [ 1 -5 -1  3]]


In [63]:
print(np.diff(groc_price_2, n=1))

[[ 1  1  1  5]
 [ 1 -5 -1  3]]


In [64]:
print(np.diff(groc_price_2, n=4))

[[  4]
 [-10]]
