# Intro to Numpy

## Creating and working with arrays

In [17]:
import numpy as np

In [29]:
x = [1, 2, 3, 4, 5]
y = ('a','b', 'c')
z = {1,2,3, 'a', 'b', 'c'}
zz =[1,2,3, 'a', 'b', 'c']

In [19]:
x_arr = np.array(x)
print(x_arr)
print(type(x_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
print(x)
print(x_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [21]:
y_arr = np.array(y)
print(y_arr)

['a' 'b' 'c']


In [26]:
z_arr = np.array(z)
print(z_arr)

{1, 2, 3, 'c', 'b', 'a'}


In [30]:
zz_arr = np.array(zz)
print(zz_arr)
print(zz)

['1' '2' '3' 'a' 'b' 'c']
[1, 2, 3, 'a', 'b', 'c']


In [31]:
t = (('a', 'b'), ('c', 'd')) #tuple containing tuples

In [32]:
t_arr = np.array(t) # creates a 2-dimensional array 
print(t_arr)

[['a' 'b']
 ['c' 'd']]


In [33]:
u = (('e','f',),('g', )) # uneven number of values creates an "inhomogenous shape" 

In [34]:
u_arr = np.array(u)
print(u_arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [35]:
u2 = (('e','f',),('g', None )) # np.nan works better with calculations and can prevent error messages but none will still work.

In [37]:
u2_arr = np.array(u2)
print(u2_arr)

[['e' 'f']
 ['g' None]]


2-dimension (2 nested set of brakets) 

In [40]:
m_arr = np.array('m')
print(m_arr)
print(type(m_arr))

m
<class 'numpy.ndarray'>


In [49]:
too_much = np.array([([1,2,1,2],[3,4,3,4]),([5,6,5,6],[7,8,7,8])])
print(too_much)
print(type(too_much))

[[[1 2 1 2]
  [3 4 3 4]]

 [[5 6 5 6]
  [7 8 7 8]]]
<class 'numpy.ndarray'>


In [50]:
too_much.ndim  #how many dimesnions somethihng has 

3

In [51]:
too_much.size #size of array 

16

In [52]:
too_much.shape # how many elements are stored in arrays 

(2, 2, 4)

In [53]:
print(too_much.T)

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]

 [[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [54]:
print(too_much)

[[[1 2 1 2]
  [3 4 3 4]]

 [[5 6 5 6]
  [7 8 7 8]]]


In [60]:
print(too_much[0][0][3]) #indexing also works with arrays 

2
