# Continuing with Numpy

In [4]:
# lists of lists (stadnard python object)

[[1, 2, 3,], ['a', 'b', 'c']]

[[1, 2, 3], ['a', 'b', 'c']]

In [12]:
print(example)

[[1, 2, 3], ['a', 'b', 'c']]


In [5]:
import numpy as np

In [6]:
example_a = np.array(example)

In [7]:
print(example)

[[1, 2, 3], ['a', 'b', 'c']]


In [11]:
example_a.dtype

dtype('<U21')

In [14]:
# another python list example

example2 = [(10,11),(12,13),(14,15)] # list of tuples only include integers 

example_b = np.array(example2)
print(example_b)
print(example_b.dtype)

[[10 11]
 [12 13]
 [14 15]]
int64


In [17]:
example3 = ((1.0,1.1),(2.0,2.1)) # tuple of tuples using floats (floats take up more space in memory than integers )

example_c = np.array(example3)
print(example_c)
print(example_c.dtype)

[[1.  1.1]
 [2.  2.1]]
float64


In [18]:
example_d = np.array(example3, dtype='i')

In [21]:
print(example_d)
print(example_d.dtype)

[[1 1]
 [2 2]]
int32


In [22]:
example_e = np.array(example1, dtype='i') # example 1 includes a mix of int and string values 

NameError: name 'example1' is not defined